### ISSUE TITLE
how to run a test in local(win 10 or ubuntu?)

### ISSUE THREAD

**Issue by chenjinhua1993** [PhilippSchindler/hydrand#1]
hello,i am a student of university. My  research orientation is information security and blockchain. I am very interesting in what you have proposed——hydrand，but pooring in programming limited me to make the next step——applying and extending your result.would you mind writing down how to make a local test specially？thank you very much！！（it doesn't matter if you were unwilling. ）

**Comment by PhilippSchindler** [comment]
Hello,

Thank for your interest in the HydRand protocol.
I will update the README file in the next few days and add a section
describing how to start the protocol locally for testing.

Which university are you studying at?

Best greating from Vienna,
Philipp





Am Mo., 15. Apr. 2019 um 16:51 Uhr schrieb chenjinhua1993 <
notifications@github.com>:

**Comment by chenjinhua1993** [comment]
thank you very much,Mr.Schindler！i am a graduate student from south china normal university. my previous is Electrical automation, now i turn my direction to computer science(security).This is a whole new area and i am exciting!

**Comment by PhilippSchindler** [comment]
hello,

I updated the github page.
see the instruction at
https://github.com/PhilippSchindler/hydrand#running-hydrand-on-a-single-machine

Am Mi., 17. Apr. 2019 um 09:40 Uhr schrieb chenjinhua1993 <
notifications@github.com>:

**Comment by chenjinhua1993** [comment]
appreciate！sorry about replying you so late.
