### ISSUE TITLE
How to use HydRand in my own code?

### ISSUE THREAD

**Issue by Lei-source-cell** [PhilippSchindler/hydrand#15]
Hi sir. I am a student from Beihang university. And I want to apply your work in my experiment.
HydRand is regarded as a black box for providing randomness, so i hope it can run one round when i call it.
It's very kind if you have any advices about my the way to call the HydRand in the main function.

Thanks for your reading and your contribution.

**Comment by PhilippSchindler** [comment]
Hi, HydRand would typically be used in for continuous operation. See the, for example, the [`evaluation/aws`](https://github.com/PhilippSchindler/HydRand/tree/master/evaluation/aws) folder for how to test the protocol on a number of AWS instances. Please be aware that the code in this repository is a research prototype. In my current capacity, I cannot offer any further technical advice.
