### ISSUE TITLE
4 faults appear in “pytest” locally？

### ISSUE THREAD

**Issue by chenjinhua1993** [PhilippSchindler/hydrand#2]
Dear Dr.Schindler,
    Recently， i studied some knowledge about your paper and "RoundHound and RandHerd".The method last time you update in README， i have tried, and that is all right.But 4 faults appeared when i try “pytest”，maybe some setting i missing during test duration.Here is the photo. I don't know if the faults are set to simulate or not？Here is pictures i catch：
![Image 1](https://user-images.githubusercontent.com/35960345/57347860-64127b80-7186-11e9-8f80-a42761b5df83.png)
![Image 2](https://user-images.githubusercontent.com/35960345/57347861-64127b80-7186-11e9-96c3-e71148aeee66.png)

**Comment by chenjinhua1993** [comment]
well,i know what happen.

**Comment by PhilippSchindler** [comment]
Sorry, I'm having trouble to reproduce this error.
Does it also show up if you run the failing tests one by one?

**Comment by chenjinhua1993** [comment]
Thanks for you replying, when i run node one by one ,it's okay. And the file in output folder print okay also.,but "pytest" can not.
Is there different between "one by one mode" and "pytest" mode? As i read your code , it  seems no different except a "pytest" round can run automatically?

**Comment by chenjinhua1993** [comment]
If you have never met that situation，it would be some setting is  wrong in my computer. I will try to fix it.

**Comment by PhilippSchindler** [comment]
What I meant by "one by one" is that you can try run each test case which fails individually with pytest. 
You can run a single test with pytest using the following command: ```pytest test_mod.py::test_func```
See [https://docs.pytest.org/en/latest/usage.html](https://docs.pytest.org/en/latest/usage.html) for more information on pytest. In case something is wrong with the setup/teardown of the tests this might help.

Anyway I think I have just located and fixed a bug in the testcases related to this issue.
Could you please pull the recent version and check if the issue persists at your computer?

**Comment by chenjinhua1993** [comment]
Okay，i will try and feedback in the following days and . Thanks for your guidance!

**Comment by chenjinhua1993** [comment]
Hi，Sir！Sorry for replying you so late.
    Recently i have test them one by one with the latest version and the old one. Comparing to the old one , what l found is that the problem is in "test_node_stepwise.py" during my test process.To sum up, in the old one , there are none of initial conditions such as  "List, N,node,...",so it could not be started. In the new one ，those parameters has been imported successfully.So ,i guess that's the reason why it works.I don't know my conjecture is right or not.

    Another question, is this project bases on a p2p network built by this system itself?

   what's more, some error still appear.But i think that is set to test robust of HydRand. In the end of your paper , a example was provided for showing the process of this system. In that demo , some Dishonest nodes was selected deliberately. Is my guess right? well, i show the picture here.
  Anyway , in this time all the test file is passed.Thank you very much.

![test_node_stepwise_1](https://user-images.githubusercontent.com/35960345/59240796-d79d2200-8c37-11e9-8d18-162ecb50e99d.png)
![test_node_stepwise_2](https://user-images.githubusercontent.com/35960345/59240809-e1bf2080-8c37-11e9-89ea-313895629d22.png)
![test_node_stepwise_3](https://user-images.githubusercontent.com/35960345/59240815-e8e62e80-8c37-11e9-8bb2-666d3ee5697a.png)

**Comment by PhilippSchindler** [comment]
Hello,

Thank you for checking that it all works on your system as well.

The communication setting is a P2P network. In contrast to e.g. Bitcoin or Ethereum, each party is connected to all other parties directly. We use the (py-)zmq library to implement the communication layer.
If I understand you correctly, your guess is right.

The errors above are only in the logging, the log function expects a timeout parameter, which is None because there is no notion of time (and consequently no timeouts) in the "stepwise"-tests.

**Comment by chenjinhua1993** [comment]
Thank you very much！
