### ISSUE TITLE
PVSS,Scalar datatype?

### ISSUE THREAD

**Issue by chenjinhua1993** [PhilippSchindler/hydrand#4]
Dear sir,
    I notice that no matter what "keypair" or "secret" in HydRand,all of them is Scalar data type.Is there any way to use my own data? For example, i want to share a string message "hello,world!".  How to transfer str to Scalar, and after recover , the secret is  still a Scalar type value. How to transfer Scalar to a str?

    I have tried the method "deterministic_random_scalar(purpose: Optional[str] = None, counter: Optional[int] = None)" in hydrand/utils.py , i think this is the way to Scalar, but i can't find a way back to string.

**Comment by PhilippSchindler** [comment]
The PVSS as used in HydRand can only be used to share a random group
element. If you want to share a specific message, it is bet to derive a
symmetric encryption key from the shared group element and use a symmetric
key encryption algorithm to encrypt your data used the derived key. This
approach is describe e.g. by Schoenmakers (
https://link.springer.com/content/pdf/10.1007/3-540-48405-1_10.pdf) in more
detail.

chenjinhua1993 <notifications@github.com> schrieb am Mo., 18. Nov. 2019,
03:26:

**Comment by chenjinhua1993** [comment]
Thank you very much !
