### ISSUE TITLE
About the throughput?

### ISSUE THREAD

**Issue by MillionaireChen** [PhilippSchindler/hydrand#6]
hi, sir!  could you tell me about how to test throughout of HydRand? using some tools like ab, iperf or something else?

**Comment by PhilippSchindler** [comment]
Hi,

You can find additional information on how we benchmarked our solution in
the evaluation/aws directory. In particular have a look at manage.py (the
run_benchmark procedure).
For measuring CPU and network we use dstat, in particular did run
dstat --integer --noupdate -T -n --tcp --cpu --mem --output ~/stats.log 1
&> /dev/null & (line 764, manage.py) in the background on all nodes during
execution of the protocol.

But I guess some other tools would work fine as well.



Am So., 28. Juni 2020 um 14:35 Uhr schrieb chenjinhua1993 <
notifications@github.com>:

**Comment by MillionaireChen** [comment]
I truly appreciate your timely help. I found that and will test later.
